Import Shop

NPCStates = {1: "AYYYY WHATS GOOOIN ON BIG GUY? I AINT SEES YOU ROUND HERE YET. YOU WANNA BUY SOMETHIN??",
             2: "WAIT A SECOND ARE U DA GUY WHO BEAT THE BLUE HAIRED VAMPIRE BICH? DATS CRAZY! HOWD YOU GET PAST THAT WORLD CLASS SUCC!?",
             3: "JEEZUS MAN YA COVERED IN GOOP! WAIT DOES THAT MEAN YOU DEFEATED THE FLEM SPITTER?! INCREDABLE! HAVE A POTION ON DA HOUSE.",
             4: " EY MAN, LEMME TELL YA SOMETHING! IF YA EVER SEE A GUY NAMED KOBE TELL HIM TO STOP MOOCHIN!... ANYWAYS YOU WANT SOMETHIN?",
             5: ""}
